@server = http://localhost:8090
###
GET {{server}}
###
GET {{server}}/steams
###
GET {{server}}/steams/2
###
GET {{server}}/steams?size=2
###
GET {{server}}/steams?size=2&page=1
###
GET {{server}}/steams?sort=nombre,desc
###
GET {{server}}/steams?sort=nombre,asc
###
GET {{server}}/steams?sort=usuario,desc
###
GET {{server}}/steams?sort=usuario,asc
###
POST {{server}}/steams
Content-Type: application/json

{"nombre": "Yu Gi Oh", "usuario": "Jacob", "identificador": 2323}

###
DELETE {{server}}/steams/5
### PATCH es Actualizar y el campo que deseas modificar
PATCH {{server}}/steams/6
Content-Type: application/json

{"nombre": "Yu Gi Oh update"}

###
GET {{server}}/profile/steams

### buscar por nombre si están separados por espacio en blanco usar el +
GET {{server}}/steams/search/findByNombre?nombre=Yu+Gi+Oh+update

######################## directorios #################
GET {{server}}/directorios
###
POST {{server}}/directorios
Content-Type: application/json

{"nombre": "Web"}

### entro steams codigo 2 y me trae la carrera que coincida
GET {{server}}/steams/2/directorio
###
GET {{server}}/directorios/2
### entro a carreras con codigo 1 y me trae todos los steams que coincidan
GET {{server}}/directorios/2/steams
###
